### ISSUE TITLE
Embed-function

### ISSUE THREAD

**Issue by drgh0st** [pep-dortmund/toolbox-workshop#129]
Include the Function embed() from IPython to the workshop.
Its one of the best ways to debug your own code.

**Comment by LuckyJosh** [comment]
I have already added an example,see PullRequest #127 ;)



Von unterwegs versendet.

-------- Ursprüngliche Nachricht --------
Von: Alex Wolf <notifications@github.com> 
Datum: 01.10.17  09:26  (GMT+01:00) 
An: pep-dortmund/toolbox-workshop <toolbox-workshop@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [pep-dortmund/toolbox-workshop] Embed-function (#129) 

Include the Function embed() from IPython to the workshop.

Its one of the best ways to debug your own code.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/pep-dortmund/toolbox-workshop","title":"pep-dortmund/toolbox-workshop","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/pep-dortmund/toolbox-workshop"}},"updates":{"snippets":[{"icon":"DESCRIPTION","message":"Embed-function (#129)"}],"action":{"name":"View Issue","url":"https://github.com/pep-dortmund/toolbox-workshop/issues/129"}}}

**Comment by LuckyJosh** [comment]
Closed by #152
