### ISSUE TITLE
VSCodium Name hat sich geändert

### ISSUE THREAD

**Issue by marcelkebe** [pep-dortmund/toolbox-workshop#205]
Debian, Ubuntu, Mint:

Ladet die Datei vscodium_<VERSION>_amd64.deb von https://github.com/VSCodium/vscodium/releases herunter und öffnet sie mit dem Software Center (Doppelklick auf den Download). Klickt auf Installieren

Datei heißt jetzt: codium_<VERSION>_amd64.deb

**Comment by LuckyJosh** [comment]
Danke ;)Von unterwegs versendet.

-------- Ursprüngliche Nachricht --------
Von: Marcel Kebekus <notifications@github.com> 
Datum: 27.09.19  16:21  (GMT+01:00) 
An: pep-dortmund/toolbox-workshop <toolbox-workshop@noreply.github.com> 
Cc: Subscribed <subscribed@noreply.github.com> 
Betreff: [pep-dortmund/toolbox-workshop] VSCodium Name hat sich geändert (#205) 

Debian, Ubuntu, Mint:

Ladet die Datei vscodium__amd64.deb von https://github.com/VSCodium/vscodium/releases herunter und öffnet sie mit dem Software Center (Doppelklick auf den Download). Klickt auf Installieren

Datei heißt jetzt: codium__amd64.deb



—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

[

{

"@context": "http://schema.org",

"@type": "EmailMessage",

"potentialAction": {

"@type": "ViewAction",

"target": "https://github.com/pep-dortmund/toolbox-workshop/issues/205?email_source=notifications\u0026email_token=ABKZUGS4F6COUMQ7XJOPQ4LQLYJFRA5CNFSM4I3HBGBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOFMMHA",

"url": "https://github.com/pep-dortmund/toolbox-workshop/issues/205?email_source=notifications\u0026email_token=ABKZUGS4F6COUMQ7XJOPQ4LQLYJFRA5CNFSM4I3HBGBKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4HOFMMHA",

"name": "View Issue"

},

"description": "View this Issue on GitHub",

"publisher": {

"@type": "Organization",

"name": "GitHub",

"url": "https://github.com"

}

}

]
