### ISSUE TITLE
Description of find command misleading

### ISSUE THREAD

**Issue by ChAr-De** [pep-dortmund/toolbox-workshop#371]
The description in the UNIX part for the find command is misleading. On slide 12 the command `find . -exec <befehl> \;` is described as `Befehl für jede gefundene Datei ausführen, {} wird durch den Dateinamen ersetzt`. There are no `{}` in the command.
Additionally the `<befehl>` should be replaced with `<command>` like on slide 13.

**Comment by maxnoe** [comment]
> Befehl für jede gefundene Datei ausführen, {} wird durch den Dateinamen ersetzt. 

This is correct.

>  There are no {} in the command.

The command is not shown, so how can there be?

Minmal example could be:

```
$ find . -exec echo "Found file: {}" \;
```

**Comment by ChAr-De** [comment]
My bad, I'm sorry.

**Comment by aknierim** [comment]
> Befehl für jede gefundene Datei ausführen, {} wird durch den Dateinamen ersetzt

I think what @ChAr-De  meant was that this part is a bit confusing for someone new to UNIX/terminals. It is absolutely correct that `{}` shows the file name. However, I think we should rephrase that latter part somewhere along the line of "Wird `{}` eingegeben, wird der gefundene Dateiname an dieser Stelle eingesetzt". Otherwise one could be confused and think we meant the `<>`.


> Minmal example could be:
> ```
> $ find . -exec echo "Found file: {}" \;
> ```
We could also provide this example of yours to show one use-case directly...
